haskell-unordered-containers/hashable

.travis.yml, Data/Hashable/Class.hs
This is available starting with GHC 7.10.0.20150307 (see
ghc/ghc@b2b1c8d4623db6f8fe38afbe59a8adcf0815056d) and avoids having to
import the unsafe `Data.Typeable.Internal` module while providing some
level of forward compatibility regarding changes to the internal
representation of `TypeRep`.
NB: This will break compilation with the exisiting GHC 7.10.1 RC1 and
RC2 snapshots
=> Use new 'typeRepHash' field accessor for GHC>=7.10

Data/Hashable/Class.hs
This renaming occurred in 842028b4a624e639dc9ee9a4f92fc208c8206e3f
Without this change `hashable` fails to build with HEAD.
=> Propagate renaming of typeRepHash to typeRepFingerprint

Data/Hashable/Class.hs
Resolve https://github.com/tibbe/hashable/issues/93 and https://github.com/tibbe/hashable/issues/94
Also add `instance Hashable (Fixed a)` when base >= 4.7 (type was opaque before that)
=> Add instances for Unique, Version and Fixed

.travis.yml, Data/Hashable/Class.hs, benchmarks/Benchmarks.hs, hashable.cabal
Based on https://github.com/tibbe/hashable/pull/102, I did some local benchmarks; for some reason this version is ~ half of time for every `hash/String` benchmark (i.e. faster).
Related to https://github.com/tibbe/hashable/issues/74
I could add `hashWithSalt len` to tuple instances too, so `((a, b), c)` and `(a,b,c)` will have different hashes.
=> List with length

Data/Hashable/Class.hs
Data.Unique has existed since `base` 3 with all the functionality we require; no need to filter to 4.8+. 
This instance was added in @hvr's patch for #101, but it basically works everywhere.
=> Remove the base version guard on `Hashable Unique`.

Data/Hashable/Class.hs
These were provided previously by the `semigroups` package
See also https://github.com/ekmett/semigroups/issues/56
=> Conditionally provide instances for NonEmpty and Semigroup newtypes

benchmarks/cbits/siphash.h, hashable.cabal
Currently, the benchmarks fail to compile when obtained from Hackage since a header file (`siphash.h`) is not bundled in the tarball via `cabal sdist`. This PR explicitly adds it to `hashable.cabal`.
See also https://github.com/fpco/stackage/issues/1372#issuecomment-213020065
=> Fix compilation of benchmarks

Data/Hashable.hs
Supposed to save time spent on calculating hashes in lookups and other operations in `unordered-containers`.
=> Added Hashed type for caching the 'hash' function result.

Data/Hashable.hs, Data/Hashable/Class.hs, Data/Hashable/Generic.hs, Data/Hashable/Lifted.hs, benchmarks/Benchmarks.hs, examples/Main.hs, hashable.cabal, tests/Properties.hs
This implements what is proposed in https://github.com/tibbe/hashable/issues/114. It is not yet complete. I still need to add more instances. There are two deviations from the original proposal:
1. The method `liftHash` is not included. The reason for this are found in the documentation in `Data.Hashable.Lifted`.
2. The `Hashable2` class was included as well. This is mostly for consistency with other packages that provide higher rank typeclass variants.
In some of existing `Hashable` instances, I call `hashWithSalt1` to avoid duplicating code. You can look at the instance for `[]` to see this. I do not believe that this will hurt performance because the inliner should expand these.
The example instances I provide in `Data.Hashable.Lifted` have not been typechecked and are likely broken. …
=> Higher kinded classes

.travis.yml, Data/Hashable.hs, Data/Hashable/Class.hs
Especially `traverseHashed` which is a `Lens (Hashed a) (Hashed b) a b` can prove to be useful (there could be `Iso`, but we'd need a `profunctors` for that, which we cannot have here).
=> Add some hashed operations from classes that cannot be implemented

CHANGES.md, Data/Hashable.hs, Data/Hashable/Class.hs, hashable.cabal
My bad I didn't realise `Class` isn't re-exported fully.
=> Export Hashable1 and Hashable2

CHANGES.md, Data/Hashable.hs, hashable.cabal
This reverts commit 2d00fec91b929189c82860941243f52bbe151e1a.
The classes are exported from `Data.Hashable.Lifted`, I'm not sure whether there's point to re-export them.
=> Revert "Export Hashable1 and Hashable2"

Data/Hashable/Generic.hs, tests/Regress.hs
Fixes #135
I didn't add `GENERICS` cpp guards, if we are going to drop support for 7.0 anyway (as in https://github.com/tibbe/hashable/pull/134)
ping @andrewthad
=> Rework the Generic hashable for sums

Data/Hashable/Class.hs
typeRepFingerprint won't be exposed in Type.Reflection, but instead is
available via Type.Reflection.Unsafe.
=> Use typeRepFingerprint from Type.Reflection.Unsafe

Data/Hashable/Class.hs
The Eq instance for Arg ignores the second argument; therefore, the Hashable
instance must also ignore the second argument, lest two equal values have
different hashes.
=> Do not hash the second argument of Arg

hashable.cabal
Found myself needing this bumped to build a project.
=> Bump bytestring dependency upper bound to < 0.12

CHANGES.md, hashable.cabal
Thus it is build by CI.
Also we can remove a flag which has no effect on a library
whatsoever.
=> Make hashable-examples a test-suite

hashable.cabal, src/Data/Hashable/Class.hs, tests/Regress.hs
Closes #214, supersedes #216. Tested with 
```cabal
packages: .
tests: True
source-repository-package
type: git
location: https://github.com/haskell/text
tag: 2.0-rc1
```
I've uploaded `text-2.0-rc1` on Hackage: https://hackage.haskell.org/package/text-2.0/candidate
=> Support text-2.0

CHANGES.md, hashable.cabal, src/Data/Hashable.hs, src/Data/Hashable/Class.hs, tests/Regress.hs
as `hash (0, ....)` would easily cause all zeros state.
- Export `defaultHash` and `defaultHashWithSalt`
=> Fix #271: Don't define `hash` for tuples

.gitattributes
GitHub classifies this repo as C++ one currently
=> Exclude xxHash-0.8.2 folder from language detection scan

CHANGES.md, hashable.cabal
In benchmarks it's own, because if you care about speed, you'll enable it.
Closes #310
=> Turn arch-native flag off by default

.github/workflows/haskell-ci.yml, cabal.project, hashable.cabal
=> Support GHC-9.12.1
